apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    fluxcd.io/sync-checksum: fa24c38347127f29c9079bee233a714cf4ea215b
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{"fluxcd.io/sync-checksum":"fa24c38347127f29c9079bee233a714cf4ea215b"},"labels":{"app":"team24-backend","fluxcd.io/sync-gc-mark":"sha256.MVtvcivLBong1Uptk1VbRGvEaS3vGhEw9orQUV80NcY"},"name":"team24-backend","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"team24-backend"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"labels":{"app":"team24-backend"}},"spec":{"containers":[{"image":"trirong/team24-backend:v0.2","imagePullPolicy":"IfNotPresent","name":"team24-backend"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","terminationGracePeriodSeconds":30}}}}
  creationTimestamp: "2020-05-24T14:58:47Z"
  generation: 1
  labels:
    app: team24-backend
    fluxcd.io/sync-gc-mark: sha256.MVtvcivLBong1Uptk1VbRGvEaS3vGhEw9orQUV80NcY
  name: team24-backend
  namespace: default
  resourceVersion: "964"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/team24-backend
  uid: 11fce7a4-9dcf-11ea-9c5e-0242d610f91a
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 2147483647
  selector:
    matchLabels:
      app: team24-backend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: team24-backend
    spec:
      containers:
      - image: trirong/team24-backend:v0.2
        imagePullPolicy: IfNotPresent
        name: team24-backend
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-05-24T14:58:49Z"
    lastUpdateTime: "2020-05-24T14:58:49Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
