apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    fluxcd.io/sync-checksum: 8af3bf2d3569e28067c008ab8baec1c916f7eb89
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{"fluxcd.io/sync-checksum":"8af3bf2d3569e28067c008ab8baec1c916f7eb89"},"labels":{"app":"team24-client","fluxcd.io/sync-gc-mark":"sha256.Xfu3PbQdbTm0gnM13zBp-m4FUwpFZ27q_bnkmrPknrY"},"name":"team24-client","namespace":"default"},"spec":{"replicas":2,"selector":{"matchLabels":{"app":"team24-client"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"team24-client"}},"spec":{"containers":[{"image":"trirong/team24-client:v0.2","imagePullPolicy":"IfNotPresent","name":"team24-client"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","terminationGracePeriodSeconds":30}}}}
  creationTimestamp: "2020-05-24T14:58:47Z"
  generation: 1
  labels:
    app: team24-client
    fluxcd.io/sync-gc-mark: sha256.Xfu3PbQdbTm0gnM13zBp-m4FUwpFZ27q_bnkmrPknrY
  name: team24-client
  namespace: default
  resourceVersion: "972"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/team24-client
  uid: 1204b034-9dcf-11ea-9c5e-0242d610f91a
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 2
  revisionHistoryLimit: 2147483647
  selector:
    matchLabels:
      app: team24-client
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: team24-client
    spec:
      containers:
      - image: trirong/team24-client:v0.2
        imagePullPolicy: IfNotPresent
        name: team24-client
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: "2020-05-24T14:58:49Z"
    lastUpdateTime: "2020-05-24T14:58:49Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 2
  replicas: 2
  updatedReplicas: 2
