apiVersion: v1
kind: Service
metadata:
  labels:
    app: team24-client
  name: team24-client
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: team24-client
  sessionAffinity: None
  type: LoadBalancer