apiVersion: v1
kind: Service
metadata:
  labels:
    app: team24-backend
  name: team24-backend
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: team24-backend
  sessionAffinity: None
  type: LoadBalancer
