apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: hasher
  name: hasher
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: hasher
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hasher
    spec:
      containers:
      - image: toeikanta/hasher:v0.1
        imagePullPolicy: IfNotPresent
        name: hasher
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
